FROM alpine:3.11

LABEL author='Daniel Nieto <d.nieto@ucm.es>'

ARG ASSETS_PASSWORD

RUN apk update && apk add bash tcsh perl gfortran gcc make libc-dev wget

RUN wget --user CTA --password ${ASSETS_PASSWORD} http://sagan.gae.ucm.es/\~nieto/cta/sims/software/corsika-76300f.tar.gz -P /

COPY ./assets/install.sh /

RUN bash /install.sh && rm /install.sh

WORKDIR /opt/

CMD bash