FROM ubuntu:20.04

LABEL author='Daniel Nieto <d.nieto@ucm.es>'

RUN apt-get update && apt-get install -y patch csh perl gfortran make g++ bc

COPY ./assets/corsika7.6_simtelarray_2019-05-29_2020-04-30.tar.gz /

COPY ./assets/install.sh /

RUN bash /install.sh && rm /install.sh
