FROM ubuntu

MAINTAINER d.nieto@ucm.es

RUN apt-get update && apt-get install -y patch csh perl perl-Data-Dumper gfortran make g++ bc

COPY ./assets/corsika7.6_simtelarray_2019-05-29_2020-04-30.tar.gz /home/

COPY ./assets/install.sh /home/

RUN cd /home/ && bash install.sh && rm install.sh
