FROM alpine:3.11

LABEL author='Daniel Nieto <d.nieto@ucm.es>'

RUN apk update && apk add bash tcsh perl gfortran gcc make libc-dev

COPY ./assets/corsika-76300f.tar.gz /

COPY ./assets/install.sh /

RUN bash /install.sh && rm /install.sh
