FROM sl:7

LABEL author='Daniel Nieto <d.nieto@ucm.es>'

ARG ASSETS_PASSWORD

RUN yum update && yum install -y patch csh perl perl-Data-Dumper gcc-gfortran make wget

RUN  wget --user CTA --password ${ASSETS_PASSWORD} http://sagan.gae.ucm.es/\~nieto/cta/sims/software/corsika-76300f.tar.gz -P /

COPY ./assets/install.sh /

RUN bash /install.sh && rm /install.sh

WORKDIR /opt/

CMD bash